name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main          # or whatever branch you use (e.g., master)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build (Jekyll)
        uses: actions/jekyll-build-pages@v1
        # the action reads your Gemfile and runs `bundle install` then `bundle exec jekyll build`

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site   # Jekyll output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
